language: scala

sudo: false

dist: xenial

scala:
  - 2.12.10
  - 2.13.1

jdk:
  - openjdk8

matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.10

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt "scalafmtCheck" "test:scalafmtCheck" "scalafmtSbtCheck" "++${TRAVIS_SCALA_VERSION} -v" test
