name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 23 * * 5'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: temurin
    - uses: sbt/setup-sbt@v1
    - run: git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
    - run: git show --oneline --check
    - run: sbt -v
           "+ scalafmtCheckAll"
           scalafmtSbtCheck
           "+ test"
